apiVersion: apps/v1
kind: Deployment
metadata:
  name: ak3s-web
  labels:
    app: ak3s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ak3s-app
  template:
    metadata:
      labels:
        app: ak3s-app
    spec:
      containers:
      - name: ak3s-ct
        image: ghcr.io/mosithean/ak3s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ghcr-mo-json-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ak3s-svc
spec:
  selector:
    app: ak3s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ak3s-cert
  namespace: default
spec:
  secretName: ak3s-tls-secret
  issuerRef:
    name: letsencrypt-prod-issuer
    kind: ClusterIssuer
  dnsNames:
  - ak3s.mosithean.tk
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ak3s-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`ak3s.mosithean.tk`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: ak3s-svc
      port: 80
  tls:
    secretName: ak3s-tls-secret
