kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: ghcr-mo-json-secret
  labels:
    repository: ghcr.io
    user: mosithean
    app: ak3s
data:
  .dockerconfigjson: `echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$TOKEN\"}}}" | base64 -w0`
